executor: slurm
default-resources:
  slurm_account: fc_elsgroup
  slurm_partition: savio2
  mem: 1000
  runtime: 60
  cpus_per_task: 1
  job_name: smk-{rule}-{wildcards}
  output: logs/{rule}/{rule}-{wildcards}-%j.out

restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
