# example -- results: "/global/home/users/yourname/Bradyrhizobium_PDS_analysis/"
home_dir: ""
#------------------------------------
# Analysis options
#------------------------------------
# example -- results: "/global/home/users/yourname/Bradyrhizobium_PDS_analysis/results"
results: ""

#------------------------------------
# Resource options
#------------------------------------
# example -- results: "/global/home/users/yourname/Bradyrhizobium_PDS_analysis/resources"
resources: ""

# example -- results: "/global/home/users/yourname/Bradyrhizobium_PDS_analysis/resources/input"
input_dir: ""
