# example -- analysis_dir: "/global/home/users/yourname/Bradyrhizobium_PDS_analysis/"
analysis_dir: ""
#------------------------------------
# Analysis options
#------------------------------------
# example -- results: "/global/home/users/yourname/Bradyrhizobium_PDS_analysis/results/"
results: ""

#------------------------------------
# Resource options
#------------------------------------
# example -- resources: "/global/home/users/yourname/Bradyrhizobium_PDS_analysis/resources/"
resources: ""

# example -- input_dir: "/global/home/users/yourname/Bradyrhizobium_PDS_analysis/resources/input/"
input_dir: ""
